/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.complitex.pspoffice.report.entity;

/**
 *
 * @author Artem
 */
public enum F3ReferenceField implements IReportField {
    NAME, ADDRESS, LIVING_AREA, APARTMENT_AREA, TAKES_ROOMS, ROOMS, FLOOR, FLOORS, PERSONAL_ACCOUNT_OWNER,
    FORM_OWNERSHIP, FACILITIES, TECHNICAL_STATE, COUNT,
    NAME0, RELATION0, BIRTH_DATE0, REGISTRATION_DATE0,
    NAME1, RELATION1, BIRTH_DATE1, REGISTRATION_DATE1,
    NAME2, RELATION2, BIRTH_DATE2, REGISTRATION_DATE2,
    NAME3, RELATION3, BIRTH_DATE3, REGISTRATION_DATE3,
    NAME4, RELATION4, BIRTH_DATE4, REGISTRATION_DATE4,
    NAME5, RELATION5, BIRTH_DATE5, REGISTRATION_DATE5,
    NAME6, RELATION6, BIRTH_DATE6, REGISTRATION_DATE6,
    NAME7, RELATION7, BIRTH_DATE7, REGISTRATION_DATE7,
    FAMILY0, FAMILY_SIZE0, FAMILY_ROOMS0, FAMILY_AREA0,
    FAMILY1, FAMILY_SIZE1, FAMILY_ROOMS1, FAMILY_AREA1,
    FAMILY2, FAMILY_SIZE2, FAMILY_ROOMS2, FAMILY_AREA2,
    FAMILY3, FAMILY_SIZE3, FAMILY_ROOMS3, FAMILY_AREA3,
    FAMILY4, FAMILY_SIZE4, FAMILY_ROOMS4, FAMILY_AREA4,
    FAMILY5, FAMILY_SIZE5, FAMILY_ROOMS5, FAMILY_AREA5,
    FAMILY6, FAMILY_SIZE6, FAMILY_ROOMS6, FAMILY_AREA6,
    FAMILY7, FAMILY_SIZE7, FAMILY_ROOMS7, FAMILY_AREA7,
    FAMILY8, FAMILY_SIZE8, FAMILY_ROOMS8, FAMILY_AREA8,
    FAMILY9, FAMILY_SIZE9, FAMILY_ROOMS9, FAMILY_AREA9;

    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
