package org.complitex.pspoffice.report.entity;

/**
 * @author Anatoly A. Ivanov java@inheaven.ru
 *         Date: 10.06.11 17:30
 */
public enum FamilyAndHousingPaymentsField implements IReportField{
    NAME, PERSONAL_ACCOUNT, ADDRESS, FORM_OF_OWNERSHIP, STOVE_TYPE,
    NAME0, RELATION0, BIRTH_DATE0, PASSPORT0,
    NAME1, RELATION1, BIRTH_DATE1, PASSPORT1,
    NAME2, RELATION2, BIRTH_DATE2, PASSPORT2,
    NAME3, RELATION3, BIRTH_DATE3, PASSPORT3,
    NAME4, RELATION4, BIRTH_DATE4, PASSPORT4,
    NAME5, RELATION5, BIRTH_DATE5, PASSPORT5,
    NAME6, RELATION6, BIRTH_DATE6, PASSPORT6,
    COUNT,
    APARTMENT_AREA, HEATED_AREA, NORMATIVE_AREA, ROOMS, BENEFITS,
    PAYMENTS_ADJUSTED_FOR_BENEFITS, NORMATIVE_PAYMENTS,
    APARTMENT_PAYMENTS, HEAT_PAYMENTS, GAS_PAYMENTS,
    COLD_WATER_PAYMENTS, HOT_WATER_PAYMENTS, DEBT, DEBT_MONTH;

    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
