package org.complitex.pspoffice.report.entity;

/**
 * @author Anatoly A. Ivanov java@inheaven.ru
 *         Date: 08.06.11 17:05
 */
public enum RegistrationStopCouponField implements IReportField {
    FIRST_NAME, LAST_NAME, MIDDLE_NAME, PREVIOUS_NAMES,
    BIRTH_DATE, BIRTH_COUNTRY, BIRTH_REGION, BIRTH_DISTRICT, BIRTH_CITY, GENDER,
    ADDRESS_COUNTRY, ADDRESS_REGION, ADDRESS_DISTRICT, ADDRESS_CITY,
    ADDRESS_STREET, ADDRESS_BUILDING, ADDRESS_CORP, ADDRESS_APARTMENT, REGISTRATION_ORGANIZATION,
    DEPARTURE_COUNTRY, DEPARTURE_REGION, DEPARTURE_DISTRICT, DEPARTURE_CITY,
    DEPARTURE_STREET, DEPARTURE_BUILDING, DEPARTURE_CORP, DEPARTURE_APARTMENT, DEPARTURE_DATE,
    PASSPORT, BIRTH_CERTIFICATE, UKRAINE_CITIZENSHIP,
    CHILDREN0, CHILDREN1,
    ADDITIONAL_INFO0, ADDITIONAL_INFO1;
    
    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
