package org.complitex.pspoffice.report.entity;

/**
 * @author Anatoly A. Ivanov java@inheaven.ru
 *         Date: 08.06.11 17:05
 */
public enum RegistrationStopCouponField implements IReportField {

    FIRST_NAME, LAST_NAME, MIDDLE_NAME, PREVIOUS_NAMES0, PREVIOUS_NAMES1,
    BIRTH_DATE, BIRTH_COUNTRY, BIRTH_REGION, BIRTH_DISTRICT, BIRTH_CITY, GENDER,
    ADDRESS, REGISTRATION_ORGANIZATION0, REGISTRATION_ORGANIZATION1,
    DEPARTURE_COUNTRY, DEPARTURE_REGION, DEPARTURE_DISTRICT, DEPARTURE_CITY, DEPARTURE_DATE,
    PASSPORT0, PASSPORT1, PASSPORT2, BIRTH_CERTIFICATE0, BIRTH_CERTIFICATE1,
    CHILD0, CHILD1, CHILD2, CHILD3, CHILD4,
    ADDITIONAL_INFO0, ADDITIONAL_INFO1, ADDITIONAL_INFO2, ADDITIONAL_INFO3;

    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
