insert into `string_culture`(`id`, `locale_id`, `value`) values (900, 1, 'Персона'), (900, 2, 'Person');
insert into `entity`(`id`, `entity_table`, `entity_name_id`, `strategy_factory`) values (900, 'person', 900, '');
insert into `string_culture`(`id`, `locale_id`, `value`) values (901, 1, 'Регистрация'), (901, 2, 'Registration');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (900, 900, 1, 901, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (902, 1, 'Имя'), (902, 2, 'Name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (901, 900, 1, 902, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (903, 1, 'Отчество'), (903, 2, 'Middle name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (902, 900, 1, 903, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (904, 1, 'Фамилия'), (904, 2, 'Last name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (903, 900, 1, 904, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (905, 1, 'Дата рождения'), (905, 2, 'Birth date');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (904, 900, 1, 905, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (906, 1, 'Место рождения'), (906, 2, 'Place of birth');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (905, 900, 1, 906, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (907, 1, 'Пол'), (907, 2, 'Sex');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (906, 900, 1, 907, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (908, 1, 'Паспорт'), (908, 2, 'Passport');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (907, 900, 1, 908, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (909, 1, 'Адрес прибытия'), (909, 2, 'Arrived from');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (908, 900, 1, 909, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (910, 1, 'Адрес убытия'), (910, 2, 'Going to');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (909, 900, 1, 910, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (911, 1, 'Отношение к владельцу'), (911, 2, 'Relation to owner');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (910, 900, 1, 911, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (912, 1, 'Отношение к остальным проживающим'), (912, 2, 'Relation to other');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (911, 900, 0, 912, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (913, 1, 'Документ права на жилпощадь'), (913, 2, 'Rights on dwelling space');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (912, 900, 0, 913, 1);