package org.complitex.pspoffice.report.entity;

/**
 * @author Anatoly A. Ivanov java@inheaven.ru
 *         Date: 15.06.11 16:49
 */
public enum HousingPaymentsField implements IReportField{
    NAME, PERSONAL_ACCOUNT, ADDRESS, FORM_OF_OWNERSHIP,
    NAME0, RELATION0, BIRTH_DATE0, PASSPORT0,
    NAME1, RELATION1, BIRTH_DATE1, PASSPORT1,
    NAME2, RELATION2, BIRTH_DATE2, PASSPORT2,
    NAME3, RELATION3, BIRTH_DATE3, PASSPORT3,
    NAME4, RELATION4, BIRTH_DATE4, PASSPORT4,
    NAME5, RELATION5, BIRTH_DATE5, PASSPORT5,
    NAME6, RELATION6, BIRTH_DATE6, PASSPORT6,
    COUNT,
    FLOORS, LIFT, HOSTEL, FLOOR, STOVE_TYPE, APARTMENT_AREA,
    BALCONY_AREA, BENEFIT_PERSONS, NORMATIVE_AREA,
    ROOMS, BENEFITS, PAYMENTS_ADJUSTED_FOR_BENEFITS,
    NORMATIVE_PAYMENTS, APARTMENT_PAYMENTS, APARTMENT_TARIFF,
    HEAT_PAYMENTS, HEAT_TARIFF, GAS_PAYMENTS, GAS_TARIFF,
    COLD_WATER_PAYMENTS, COLD_WATER_TARIFF, HOT_WATER_PAYMENTS,
    HOT_WATER_TARIFF, OUTLET_PAYMENTS, OUTLET_TARIFF,
    COUNTERS_PRESENCE, DEBT, DEBT_MONTH;

    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
