package org.complitex.pspoffice.report.entity;

/**
 * @author Anatoly A. Ivanov java@inheaven.ru
 *         Date: 17.05.11 17:00
 */
public enum RegistrationCard implements IReportFields{
    FIRST_NAME, LAST_NAME, MIDDLE_NAME, NATIONALITY,
    BIRTH_DATE, BIRTH_REGION, BIRTH_DISTRICT, BIRTH_CITY, BIRTH_VILLAGE,
    ARRIVAL_REGION, ARRIVAL_DISTRICT, ARRIVAL_CITY, ARRIVAL_VILLAGE, ARRIVAL_DATE,
    ARRIVAL_STREET, ARRIVAL_BUILDING, ARRIVAL_CORP, ARRIVAL_APARTMENT,
    PASSPORT_SERIES0, PASSPORT_NUMBER0, PASSPORT_ISSUED0,
    PASSPORT_SERIES1, PASSPORT_NUMBER1, PASSPORT_ISSUED1,
    PASSPORT_SERIES2, PASSPORT_NUMBER2, PASSPORT_ISSUED2,
    PASSPORT_SERIES3, PASSPORT_NUMBER3, PASSPORT_ISSUED3,
    RESIDENCE_CITY, RESIDENCE_STREET, RESIDENCE_BUILDING, RESIDENCE_CORP, RESIDENCE_APARTMENT,
    WORKS0, WORKS1, CHILDREN0, CHILDREN1, CHILDREN2, MILITARY0, MILITARY1, MILITARY2,
    REGISTRATION_NOTE, REGISTRATION_DATE, REGISTRATION_TYPE,
    LEAVE_REGION, LEAVE_DISTRICT, LEAVE_CITY, LEAVE_VILLAGE, LEAVE_DATE, LEAVE_REASON;

    @Override
    public String getFieldName() {
        return name().toLowerCase();
    }
}
