insert into `string_culture`(`id`, `locale_id`, `value`) values (2000, 1, 'Персона'), (2000, 2, 'Person');
insert into `entity`(`id`, `entity_table`, `entity_name_id`, `strategy_factory`) values (2000, 'person', 2000, '');
insert into `string_culture`(`id`, `locale_id`, `value`) values (2001, 1, 'Регистрация'), (2001, 2, 'Registration');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2000, 2000, 1, 2001, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2002, 1, 'Имя'), (2002, 2, 'Name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2001, 2000, 1, 2002, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2003, 1, 'Отчество'), (2003, 2, 'Middle name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2002, 2000, 1, 2003, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2004, 1, 'Фамилия'), (2004, 2, 'Last name');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2003, 2000, 1, 2004, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2005, 1, 'Дата рождения'), (2005, 2, 'Birth date');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2004, 2000, 1, 2005, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2006, 1, 'Место рождения'), (2006, 2, 'Place of birth');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2005, 2000, 1, 2006, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2007, 1, 'Пол'), (2007, 2, 'Sex');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2006, 2000, 1, 2007, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2008, 1, 'Паспорт'), (2008, 2, 'Passport');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2007, 2000, 1, 2008, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2009, 1, 'Адрес прибытия'), (2009, 2, 'Arrived from');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2008, 2000, 1, 2009, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2010, 1, 'Адрес убытия'), (2010, 2, 'Going to');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2009, 2000, 1, 2010, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2011, 1, 'Отношение к владельцу'), (2011, 2, 'Relation to owner');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2010, 2000, 1, 2011, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2012, 1, 'Отношение к остальным проживающим'), (2012, 2, 'Relation to other');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2011, 2000, 0, 2012, 1);
insert into `string_culture`(`id`, `locale_id`, `value`) values (2013, 1, 'Документ права на жилпощадь'), (2013, 2, 'Rights on dwelling space');
insert into `entity_attribute_type`(`id`, `entity_id`, `mandatory`, `attribute_type_name_id`, `system`) values (2012, 2000, 0, 2013, 1);